from neo4j import GraphDatabase
import os
from dotenv import load_dotenv

load_dotenv()

uri = os.getenv("NEO4J_URI")
username = os.getenv("NEO4J_USER") or os.getenv("NEO4J_USERNAME")
password = os.getenv("NEO4J_PASSWORD")

driver = GraphDatabase.driver(uri, auth=(username, password))

def load_sample_data():
    with driver.session() as s:
        s.run("MATCH (n) DETACH DELETE n")
        s.run("""
        // ── BREAST CANCER GENES ──────────────────────────
        MERGE (g1:Gene {name: 'BRCA1'})
        MERGE (g2:Gene {name: 'BRCA2'})
        MERGE (g3:Gene {name: 'TP53'})
        MERGE (g4:Gene {name: 'ERBB2'})
        MERGE (g5:Gene {name: 'MYC'})
        MERGE (g6:Gene {name: 'PIK3CA'})

        // ── LUNG CANCER GENES ────────────────────────────
        MERGE (g7:Gene {name: 'EGFR'})
        MERGE (g8:Gene {name: 'ALK'})
        MERGE (g9:Gene {name: 'KRAS'})
        MERGE (g10:Gene {name: 'RET'})

        // ── COLORECTAL CANCER GENES ──────────────────────
        MERGE (g11:Gene {name: 'APC'})
        MERGE (g12:Gene {name: 'BRAF'})
        MERGE (g13:Gene {name: 'PTEN'})
        MERGE (g14:Gene {name: 'MLH1'})

        // ── MELANOMA GENES ───────────────────────────────
        MERGE (g15:Gene {name: 'BRAF_V600E'})
        MERGE (g16:Gene {name: 'NRAS'})
        MERGE (g17:Gene {name: 'CDKN2A'})

        // ── LEUKEMIA GENES ───────────────────────────────
        MERGE (g18:Gene {name: 'FLT3'})
        MERGE (g19:Gene {name: 'BCR_ABL1'})

        // ── MUTATIONS ────────────────────────────────────
        MERGE (m1:Mutation {name: 'BRCA1_mut'})
        MERGE (m2:Mutation {name: 'BRCA2_mut'})
        MERGE (m3:Mutation {name: 'TP53_mut'})
        MERGE (m4:Mutation {name: 'ERBB2_amp'})
        MERGE (m5:Mutation {name: 'MYC_cnv'})
        MERGE (m6:Mutation {name: 'PIK3CA_mut'})
        MERGE (m7:Mutation {name: 'EGFR_mut'})
        MERGE (m8:Mutation {name: 'ALK_fusion'})
        MERGE (m9:Mutation {name: 'KRAS_mut'})
        MERGE (m10:Mutation {name: 'RET_fusion'})
        MERGE (m11:Mutation {name: 'APC_mut'})
        MERGE (m12:Mutation {name: 'BRAF_mut'})
        MERGE (m13:Mutation {name: 'PTEN_loss'})
        MERGE (m14:Mutation {name: 'MLH1_mut'})
        MERGE (m15:Mutation {name: 'BRAF_V600E_mut'})
        MERGE (m16:Mutation {name: 'NRAS_mut'})
        MERGE (m17:Mutation {name: 'CDKN2A_del'})
        MERGE (m18:Mutation {name: 'FLT3_mut'})
        MERGE (m19:Mutation {name: 'BCR_ABL1_fusion'})

        // ── DRUGS ─────────────────────────────────────────
        MERGE (d1:Drug {name: 'Olaparib'})
        MERGE (d2:Drug {name: 'Pembrolizumab'})
        MERGE (d3:Drug {name: 'Trastuzumab'})
        MERGE (d4:Drug {name: 'Tamoxifen'})
        MERGE (d5:Drug {name: 'Alpelisib'})
        MERGE (d6:Drug {name: 'Osimertinib'})
        MERGE (d7:Drug {name: 'Crizotinib'})
        MERGE (d8:Drug {name: 'Sotorasib'})
        MERGE (d9:Drug {name: 'Selpercatinib'})
        MERGE (d10:Drug {name: 'Cetuximab'})
        MERGE (d11:Drug {name: 'Vemurafenib'})
        MERGE (d12:Drug {name: 'Everolimus'})
        MERGE (d13:Drug {name: 'Pembrolizumab'})
        MERGE (d14:Drug {name: 'Dabrafenib'})
        MERGE (d15:Drug {name: 'Binimetinib'})
        MERGE (d16:Drug {name: 'Ipilimumab'})
        MERGE (d17:Drug {name: 'Midostaurin'})
        MERGE (d18:Drug {name: 'Imatinib'})

        // ── OUTCOMES ──────────────────────────────────────
        MERGE (o1:Outcome {name: 'positive',  response_rate: 0.72})
        MERGE (o2:Outcome {name: 'moderate',  response_rate: 0.45})
        MERGE (o3:Outcome {name: 'positive',  response_rate: 0.81})
        MERGE (o4:Outcome {name: 'moderate',  response_rate: 0.51})
        MERGE (o5:Outcome {name: 'moderate',  response_rate: 0.64})
        MERGE (o6:Outcome {name: 'positive',  response_rate: 0.78})
        MERGE (o7:Outcome {name: 'positive',  response_rate: 0.76})
        MERGE (o8:Outcome {name: 'moderate',  response_rate: 0.58})
        MERGE (o9:Outcome {name: 'positive',  response_rate: 0.69})
        MERGE (o10:Outcome {name: 'moderate', response_rate: 0.42})
        MERGE (o11:Outcome {name: 'moderate', response_rate: 0.55})
        MERGE (o12:Outcome {name: 'positive', response_rate: 0.67})
        MERGE (o13:Outcome {name: 'moderate', response_rate: 0.49})
        MERGE (o14:Outcome {name: 'positive', response_rate: 0.63})
        MERGE (o15:Outcome {name: 'positive', response_rate: 0.73})
        MERGE (o16:Outcome {name: 'moderate', response_rate: 0.44})
        MERGE (o17:Outcome {name: 'moderate', response_rate: 0.52})
        MERGE (o18:Outcome {name: 'positive', response_rate: 0.68})
        MERGE (o19:Outcome {name: 'positive', response_rate: 0.85})

        // ── GENE → MUTATION ───────────────────────────────
        MERGE (g1)-[:HAS_MUTATION]->(m1)
        MERGE (g2)-[:HAS_MUTATION]->(m2)
        MERGE (g3)-[:HAS_MUTATION]->(m3)
        MERGE (g4)-[:HAS_MUTATION]->(m4)
        MERGE (g5)-[:HAS_MUTATION]->(m5)
        MERGE (g6)-[:HAS_MUTATION]->(m6)
        MERGE (g7)-[:HAS_MUTATION]->(m7)
        MERGE (g8)-[:HAS_MUTATION]->(m8)
        MERGE (g9)-[:HAS_MUTATION]->(m9)
        MERGE (g10)-[:HAS_MUTATION]->(m10)
        MERGE (g11)-[:HAS_MUTATION]->(m11)
        MERGE (g12)-[:HAS_MUTATION]->(m12)
        MERGE (g13)-[:HAS_MUTATION]->(m13)
        MERGE (g14)-[:HAS_MUTATION]->(m14)
        MERGE (g15)-[:HAS_MUTATION]->(m15)
        MERGE (g16)-[:HAS_MUTATION]->(m16)
        MERGE (g17)-[:HAS_MUTATION]->(m17)
        MERGE (g18)-[:HAS_MUTATION]->(m18)
        MERGE (g19)-[:HAS_MUTATION]->(m19)

        // ── MUTATION → DRUG ───────────────────────────────
        MERGE (m1)-[:TARGETED_BY]->(d1)
        MERGE (m2)-[:TARGETED_BY]->(d1)
        MERGE (m3)-[:TARGETED_BY]->(d2)
        MERGE (m4)-[:TARGETED_BY]->(d3)
        MERGE (m5)-[:TARGETED_BY]->(d4)
        MERGE (m6)-[:TARGETED_BY]->(d5)
        MERGE (m7)-[:TARGETED_BY]->(d6)
        MERGE (m8)-[:TARGETED_BY]->(d7)
        MERGE (m9)-[:TARGETED_BY]->(d8)
        MERGE (m10)-[:TARGETED_BY]->(d9)
        MERGE (m11)-[:TARGETED_BY]->(d10)
        MERGE (m12)-[:TARGETED_BY]->(d11)
        MERGE (m13)-[:TARGETED_BY]->(d12)
        MERGE (m14)-[:TARGETED_BY]->(d13)
        MERGE (m15)-[:TARGETED_BY]->(d14)
        MERGE (m16)-[:TARGETED_BY]->(d15)
        MERGE (m17)-[:TARGETED_BY]->(d16)
        MERGE (m18)-[:TARGETED_BY]->(d17)
        MERGE (m19)-[:TARGETED_BY]->(d18)

        // ── DRUG → OUTCOME ────────────────────────────────
        MERGE (d1)-[:HAS_OUTCOME]->(o1)
        MERGE (d2)-[:HAS_OUTCOME]->(o2)
        MERGE (d3)-[:HAS_OUTCOME]->(o3)
        MERGE (d4)-[:HAS_OUTCOME]->(o4)
        MERGE (d5)-[:HAS_OUTCOME]->(o5)
        MERGE (d6)-[:HAS_OUTCOME]->(o6)
        MERGE (d7)-[:HAS_OUTCOME]->(o7)
        MERGE (d8)-[:HAS_OUTCOME]->(o8)
        MERGE (d9)-[:HAS_OUTCOME]->(o9)
        MERGE (d10)-[:HAS_OUTCOME]->(o10)
        MERGE (d11)-[:HAS_OUTCOME]->(o11)
        MERGE (d12)-[:HAS_OUTCOME]->(o12)
        MERGE (d13)-[:HAS_OUTCOME]->(o13)
        MERGE (d14)-[:HAS_OUTCOME]->(o14)
        MERGE (d15)-[:HAS_OUTCOME]->(o15)
        MERGE (d16)-[:HAS_OUTCOME]->(o16)
        MERGE (d17)-[:HAS_OUTCOME]->(o17)
        MERGE (d18)-[:HAS_OUTCOME]->(o18)
        MERGE (d18)-[:HAS_OUTCOME]->(o19)
        """)
        print("Full graph loaded — 19 genes, 18 drugs across 5 cancer types!")

load_sample_data()
driver.close()
